name: Apply Infrastructure

on:
  push:
    branches:
      - main
      - producao
      - teste
  pull_request:
    branches:
      - main
      - producao
      - teste

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      # 1. Baixar o repositório
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # 3. Instalar dependências
      - name: 'Install dependencies'
        working-directory: ./app
        run: pip install -r requirements.txt

      # 4. Criar o arquivo ZIP
      - name: 'Create ZIP file'
        working-directory: ./app
        run: python upload_zip.py

      # 5. Configurar o Terraform
      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      # 6. Configurar credenciais da AWS
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 7. Inicializar o Terraform
      - name: 'Terraform Init'
        working-directory: ./terraform
        run: terraform init

      # 8. Aplicar as configurações do Terraform
      - name: 'Terraform Apply'
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Credenciais AWS
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Credenciais AWS
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Variável para o Terraform
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Variável para o Terraform
          TF_VAR_aws_region: "us-east-1"  # Região para o Terraform
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}  # Nome de usuário do banco de dados
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}  # Senha do banco de dados
        run: terraform apply -auto-approve
